language: rust
cache: cargo
rust:
  - nightly
  - stable
  - beta
os:
  - osx


before_script:
  - rustup component add rustfmt-preview
  - rustfmt --version

script:
  - cargo build --verbose
  - cargo test --verbose
  - if [ "${TRAVIS_RUST_VERSION}" = "nightly" ]; then
      cargo fmt -- --write-mode=diff;
    else
      echo "Not checking formatting on this build";
    fi

notifications:
  email:
    on_success: never
    on_failure: never
